### ISSUE TITLE
[bug] Action 'aur-publish-preview' 在prereleased时未触发

### ISSUE THREAD

**Issue by witt-bit** [EcoPasteHub/EcoPaste#789]
### Describe the bug

```yaml
on:
  release:
    types: [published]

`未触发`prereleased`

### Reproduction

_No response_

### Expected behavior

_No response_

### Software Information

```text
.
```

### Additional context

https://github.com/orgs/community/discussions/42780
提到
![image](https://github.com/user-attachments/assets/99a7f305-8ad9-4663-a883-4e025248c5ae)

而且刚开始时运行没问题，就最近两次坏了
